const Ziggy = {"url":"http:\/\/mining.test","port":null,"defaults":{},"routes":{"login":{"uri":"login","methods":["GET","HEAD"]},"logout":{"uri":"logout","methods":["POST"]},"password.request":{"uri":"forgot-password","methods":["GET","HEAD"]},"password.reset":{"uri":"reset-password\/{token}","methods":["GET","HEAD"]},"password.email":{"uri":"forgot-password","methods":["POST"]},"password.update":{"uri":"reset-password","methods":["POST"]},"register":{"uri":"register","methods":["GET","HEAD"]},"user-profile-information.update":{"uri":"user\/profile-information","methods":["PUT"]},"user-password.update":{"uri":"user\/password","methods":["PUT"]},"password.confirm":{"uri":"user\/confirm-password","methods":["GET","HEAD"]},"password.confirmation":{"uri":"user\/confirmed-password-status","methods":["GET","HEAD"]},"two-factor.login":{"uri":"two-factor-challenge","methods":["GET","HEAD"]},"profile.show":{"uri":"user\/profile","methods":["GET","HEAD"]},"other-browser-sessions.destroy":{"uri":"user\/other-browser-sessions","methods":["DELETE"]},"current-user-photo.destroy":{"uri":"user\/profile-photo","methods":["DELETE"]},"current-user.destroy":{"uri":"user","methods":["DELETE"]},"dashboard":{"uri":"dashboard","methods":["GET","HEAD"]},"miners.index":{"uri":"miners","methods":["GET","HEAD"]},"miners.create":{"uri":"miners\/create","methods":["GET","HEAD"]},"miners.store":{"uri":"miners","methods":["POST"]},"miners.show":{"uri":"miners\/{miner}","methods":["GET","HEAD"],"bindings":{"miner":"id"}},"miners.edit":{"uri":"miners\/{miner}\/edit","methods":["GET","HEAD"],"bindings":{"miner":"id"}},"miners.update":{"uri":"miners\/{miner}","methods":["PUT","PATCH"],"bindings":{"miner":"id"}},"miners.destroy":{"uri":"miners\/{miner}","methods":["DELETE"],"bindings":{"miner":"id"}},"payouts.index":{"uri":"payouts","methods":["GET","HEAD"]}}};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    for (let name in window.Ziggy.routes) {
        Ziggy.routes[name] = window.Ziggy.routes[name];
    }
}

export { Ziggy };
